name: GitHub Actions Demo

on:
  push: 
    branches: [main]
    paths-ignore: [ .github/* ]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - run: echo "The event that triggered this workfolow was $${{ github.event_name }}"
        - run: echo "The branch that triggered this workflow was $${{ github.ref }}"
        - uses: actions/checkout@v3.0.0
        - run: tree
    
